# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'the-game' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'lottie-ios'

  # Pods for the-game

  target 'the-gameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'the-gameUITests' do
    # Pods for testing
  end

end
